version: 0.2
#Nombre maximal de clignotement de redstone autorise pendant la periode "Delay"
MaxImpulsion: 150
#Temp (en secondes) avant de reset la premiere variable
Delay: 300
#Faut t'il prevenir un admin?
NotifyAdmins: true
#ecrire le texte a mettre dans les panneauxs
Sign:
  Line1: 'Les boucles de'
  Line2: 'redstone'
  Line3: 'sont'
  Line4: '&4Interdite!'
IgnoreWorlds: redstoneWorld/survie

Msg:
  default:
    prefix: '&bAntiRedstoneClock &9&l> &r&b '
    error: '&4AntiRedstoneClock &l> &r&c '
    no_permission: '&4Erreur &9&l> &r&bYou dont have permission to do that!'
    command_use: '&4SnowBallWar &l> &r&cCommand usage: &6/arc $commande'
  message:
    MsgToAdmin: 'Redstone clock disable in x:$X y:$Y Z:$Z. In the world $World'
    unknownCmd: 'Unknown command. Type "/help" for help.'
    reloadSuccess: 'Reload Success!'
  Exception:
    duplicate_object: 'This list already contains this redstone'
