name: antiRedstoneClock
version: 0.2
description: Limit the redstoneClock
author: Amosar
 
main: com.trafalcraft.antiRedstoneClock.Main

commands:
   antiRedstoneClock:
     description: Base command for the antiRedstoneClock plugin.
     aliases: [arc]
