name: antiRedstoneClock
version: 0.10
description: Limit the redstoneClock
author: Amosar
website: https://www.spigotmc.org/resources/antiredstoneclock.18557
 
main: com.trafalcraft.antiRedstoneClock.Main

commands:
   antiRedstoneClock:
     description: Base command for the antiRedstoneClock plugin.
     aliases: [arc]
